{% set version = "2.1.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-collapse
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/collapse_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/collapse/collapse_{{ version }}.tar.gz
  sha256: b13197b9e06d7ded81466fbe2560cfff9ba30281e19f5dfd01d9fa5451808209

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-rcpp                       # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - libgomp                      # [linux]
    - llvm-openmp                  # [osx]
  host:
    - r-base
    - r-rcpp >=1.0.1
    - llvm-openmp                  # [osx]
  run:
    - r-base
    - r-rcpp >=1.0.1
    - llvm-openmp                  # [osx]

test:
  commands:
    - $R -e "library('collapse')"           # [not win]
    - "\"%R%\" -e \"library('collapse')\""  # [win]

about:
  home: https://sebkrantz.github.io/collapse/
  dev_url: https://github.com/SebKrantz/collapse
  license: GPL-2.0-or-later
  summary: A C/C++ based package for advanced data transformation and statistical computing in R that is extremely fast, class-agnostic, and programmer friendly through a flexible, parsimonious, and robust API. Core functionality includes a rich set of S3 generic grouped and weighted   statistical functions for vectors,
    matrices and data frames, which provide efficient low-level vectorizations and OpenMP multithreading (reducing the   need for iteration/vectorization in R), and skip missing values by default. These are integrated with fast grouping and ordering algorithms (also callable   from C), and efficient data manipulation functions.
    The package also provides a flexible and rigorous approach to time series and panel data in R. It further   includes fast functions for common statistical procedures, detailed (grouped, weighted) summary statistics, powerful tools to work with nested data, fast   data object conversions, functions for memory efficient
    R programming, and helpers to effectively deal with variable labels, attributes, and missing data.   It is well integrated with basic R, 'dplyr'/'tibble', 'data.table', 'sf', 'plm' (panel-series and data frames), and accommodates (by virtue of smart internal   attribute handling) many other classes (like 'ts', 'xts'/'zoo'
    or 'tsibble').
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - SebKrantz
